// Round-trips EventPublisher -> LiveWireClient over a real loopback socket,
// with both halves in one process, and checks the three properties the fetch
// loop actually depends on:
//
//   1. Fidelity. Every record a reader receives is byte-identical to the one
//      published, and they arrive in order. This is what makes the shared
//      LiveWire.h header worth having; a packing or endian mistake shows up
//      here rather than as a raster full of nonsense.
//
//   2. publish() never blocks. Timed with the reader deliberately stalled,
//      so the socket's send buffer is full and the publisher thread is
//      parked in its WSAEWOULDBLOCK wait. If publish() were on the socket's
//      side of that, this is where the fetch loop would lose samples --
//      which is the whole reason EventPublisher is built the way it is.
//
//   3. Overflow drops the OLDEST and says so. A viewer that cannot keep up
//      must cost viewer data and nothing else, and the loss must be counted
//      rather than silent (same principle as StreamAccountant).
//
// Plus, for the version-2 protocol (LiveWire.h -- channel geometry preamble
// and kWireAmpChannel amplitude records for the live drift tracker):
//
//   4. The geometry preamble round-trips (per-unit channel count + x/y).
//   5. A version mismatch is refused loudly, not misparsed.
//   6. A preamble truncated mid-way through the new channel-count/geometry
//      arrays is refused loudly, not misparsed.
//   7. kWireAmpChannel records interleaved with kWireSpike records survive
//      the wire with every field routed correctly.
//   8. DriftTracker groups kWireAmpChannel records back into spikes by
//      (unit, sampleIndex) correctly even when channel records from two
//      different spikes arrive interleaved with each other.
//   9. DriftPool's pooledMedianMotion() matches
//      FilterGen/drift_estimate.pooled_com_motion()'s own pooling output on
//      a fixture generated by FilterGen/gen_drift_fixture.py -- see that
//      script's docstring for exactly what is and is not being checked.
//
// Build (from the repo root, with the MSVC env set -- see README):
//   cl.exe /EHsc /std:c++17 /Fe:TestLiveWireRoundtrip.exe ^
//       ClosedLoop\test_livewire_roundtrip.cpp ClosedLoop\EventPublisher.cpp ^
//       Viewer\LiveWireClient.cpp Viewer\DriftTracker.cpp Viewer\DriftPool.cpp ^
//       /I ClosedLoop /I Viewer
//
// Run with an optional fixture path (from
// `python FilterGen\gen_drift_fixture.py --out drift_fixture.bin`) to
// include test 9; without it, test 9 is skipped and said so, everything
// else still runs:
//   TestLiveWireRoundtrip.exe [drift_fixture.bin]

#include <iostream>
#include <vector>
#include <thread>
#include <chrono>
#include <cstring>
#include <algorithm>
#include <numeric>
#include <cmath>
#include <fstream>
#include <limits>

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <winsock2.h>
#include <ws2tcpip.h>
#pragma comment(lib, "ws2_32.lib")

#include "EventPublisher.h"
#include "LiveWireClient.h"
#include "DriftTracker.h"
#include "DriftPool.h"

namespace {

const int kTestPort = 4199;   // not the default, so this never fights a real run

int g_failures = 0;
static int g_skipped  = 0;

void check( bool cond, const std::string &what )
{
    std::cout << ( cond ? "  ok   " : "  FAIL " ) << what << "\n";
    if( !cond )
        ++g_failures;
}

// Distinct, reproducible content per record, so an ordering or aliasing bug
// cannot pass by accident.
livewire::WireRecord makeTestRecord( int i )
{
    return livewire::makeRecord(
        livewire::kWireSpike, livewire::kStreamImec,
        /*a*/ 1000 + i,
        /*sampleIndex*/ 500000000LL + i * 7LL,
        /*b*/ static_cast<float>( i ) * 0.25f,
        /*timeRelSyncS*/ static_cast<float>( i ) * 1e-4f );
}

// Waits for a condition rather than sleeping a guessed interval, so this
// test does not become flaky on a loaded machine.
template<typename F>
bool waitUntil( F pred, int timeoutMs )
{
    auto deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds( timeoutMs );
    while( std::chrono::steady_clock::now() < deadline ) {
        if( pred() )
            return true;
        std::this_thread::sleep_for( std::chrono::milliseconds( 2 ) );
    }
    return pred();
}

// -----------------------------------------------------------------------
// Minimal raw-socket server for the "malformed stream" tests (5/6 below):
// EventPublisher always sends a well-formed handshake, so testing what
// LiveWireClient does with a BAD one needs something else driving the
// listening socket. Blocking and single-shot on purpose -- these tests
// send a fixed byte string and close, nothing pipelined.
struct RawSocketInit {
    bool ok;
    RawSocketInit() { WSADATA w; ok = ( WSAStartup( MAKEWORD( 2, 2 ), &w ) == 0 ); }
};

bool ensureRawSockets()
{
    static RawSocketInit init;
    return init.ok;
}

// Listens on `port`, accepts exactly one connection, writes `bytes`
// (may be empty), then closes -- run on a background thread so the
// caller's connect() can proceed concurrently, matching how a real
// misbehaving/truncated peer would look from LiveWireClient's side.
std::thread serveOnceAndClose( int port, std::vector<char> bytes )
{
    return std::thread( [port, bytes]() {
        SOCKET ls = socket( AF_INET, SOCK_STREAM, IPPROTO_TCP );
        BOOL yes = TRUE;
        setsockopt( ls, SOL_SOCKET, SO_REUSEADDR, reinterpret_cast<const char*>( &yes ), sizeof(yes) );

        sockaddr_in addr;
        std::memset( &addr, 0, sizeof(addr) );
        addr.sin_family      = AF_INET;
        addr.sin_port        = htons( static_cast<u_short>( port ) );
        addr.sin_addr.s_addr = htonl( INADDR_LOOPBACK );

        if( bind( ls, reinterpret_cast<sockaddr*>( &addr ), sizeof(addr) ) != 0 ) {
            closesocket( ls );
            return;
        }
        listen( ls, 1 );

        SOCKET c = accept( ls, NULL, NULL );
        if( c != INVALID_SOCKET ) {
            if( !bytes.empty() )
                send( c, &bytes[0], static_cast<int>( bytes.size() ), 0 );
            closesocket( c );
        }
        closesocket( ls );
    } );
}

} // namespace


int main( int argc, char **argv )
{
    if( !ensureRawSockets() ) {
        std::cerr << "WSAStartup failed for the raw-socket tests\n";
        return 2;
    }

    std::vector<int> unitIds;
    for( int i = 0; i < 157; ++i )
        unitIds.push_back( i * 3 + 1 );   // not 0..n-1, so an index/id mix-up shows

    // -------------------------------------------------------------------
    // 1. Fidelity and ordering.
    // -------------------------------------------------------------------
    std::cout << "session header + record fidelity\n";
    {
        EventPublisher pub( kTestPort, unitIds, 30000.0, 25000.0, /*imecSy=*/true, 65536 );
        if( !pub.start() ) {
            std::cerr << "publisher failed to start -- is port " << kTestPort << " in use?\n";
            return 2;
        }

        LiveWireClient cli;
        if( !cli.connect( "127.0.0.1", kTestPort ) ) {
            std::cerr << "client failed to connect: " << cli.lastError() << "\n";
            return 2;
        }

        check( cli.header().nUnits == 157, "header nUnits" );
        check( cli.header().imecSampleRateHz == 30000.0, "header imec rate" );
        check( cli.header().niSampleRateHz == 25000.0, "header ni rate" );
        check( cli.header().syllableSourceIsImecSy == 1, "header syllableSource flag" );
        check( cli.unitIds() == unitIds, "unit id table survives the wire" );

        // publish() drops while no client is attached (by design), and the
        // publisher thread only notices the accept on its next pass.
        check( waitUntil( [&]{ return pub.hasClient(); }, 2000 ), "publisher sees the client" );

        const int kN = 20000;
        for( int i = 0; i < kN; ++i )
            pub.publish( makeTestRecord( i ) );

        std::vector<livewire::WireRecord> got;
        waitUntil( [&]{ cli.poll( got ); return static_cast<int>( got.size() ) >= kN; }, 10000 );

        check( static_cast<int>( got.size() ) == kN, "all records arrived" );

        bool identical = ( static_cast<int>( got.size() ) == kN );
        for( int i = 0; identical && i < kN; ++i ) {
            livewire::WireRecord expect = makeTestRecord( i );
            identical = ( std::memcmp( &expect, &got[i], sizeof(expect) ) == 0 );
            if( !identical )
                std::cout << "    first mismatch at record " << i << "\n";
        }
        check( identical, "every record byte-identical and in order" );
        check( pub.nDropped() == 0, "nothing dropped when the reader keeps up" );
    }

    // -------------------------------------------------------------------
    // 2. publish() does not block on a stalled reader.
    // -------------------------------------------------------------------
    std::cout << "publish() latency with the reader stalled\n";
    {
        // Small ring on purpose: this forces the overflow path to be the
        // thing being timed, not an unused branch.
        EventPublisher pub( kTestPort, unitIds, 30000.0, 0.0, false, 4096 );
        if( !pub.start() )
            return 2;

        LiveWireClient cli;
        if( !cli.connect( "127.0.0.1", kTestPort ) )
            return 2;
        waitUntil( [&]{ return pub.hasClient(); }, 2000 );

        // The client never polls below, so the socket's send buffer fills
        // and the publisher thread parks in its WSAEWOULDBLOCK wait.
        const int kN = 200000;
        std::vector<livewire::WireRecord> batch( 64 );

        std::vector<double> batchUs;
        batchUs.reserve( kN / 64 + 1 );

        auto t0 = std::chrono::steady_clock::now();
        for( int i = 0; i < kN; i += 64 ) {
            for( int j = 0; j < 64; ++j )
                batch[j] = makeTestRecord( i + j );

            auto b0 = std::chrono::steady_clock::now();
            pub.publish( &batch[0], batch.size() );
            batchUs.push_back( std::chrono::duration<double, std::micro>(
                                    std::chrono::steady_clock::now() - b0 ).count() );
        }
        double totalMs = std::chrono::duration<double, std::milli>(
                              std::chrono::steady_clock::now() - t0 ).count();

        std::vector<double> sorted( batchUs );
        std::sort( sorted.begin(), sorted.end() );
        double medianUs = sorted[sorted.size() / 2];
        double p999Us   = sorted[( sorted.size() * 999 ) / 1000];
        double worstBatchUs = sorted.back();

        // Reported as a distribution, not just a worst case: the worst is an
        // OS scheduling outlier and quoting it alone would misrepresent what
        // the fetch loop actually pays per chunk.
        std::cout << "    " << kN << " records in " << totalMs << " ms ("
                   << ( totalMs * 1000.0 / kN ) << " us/record)\n"
                   << "    per 64-record publish(): median " << medianUs
                   << " us, p99.9 " << p999Us << " us, worst " << worstBatchUs << " us\n";

        // A whole fetch chunk is 5 ms and carries at most a few hundred
        // records. Any single publish() call taking longer than a
        // millisecond would mean the socket had reached back into the fetch
        // loop; the real measured figure is orders of magnitude under this.
        check( worstBatchUs < 1000.0, "no single publish() call approaches a fetch chunk" );

        // -------------------------------------------------------------------
        // 3. Overflow drops, and is counted.
        // -------------------------------------------------------------------
        std::cout << "overflow accounting\n";
        check( pub.nDropped() > 0, "a stalled reader causes counted drops" );
        check( pub.nPublished() == kN, "published count is what the producer offered" );

        // The reader, once it resumes, must still see a valid record stream
        // (drop-oldest keeps record alignment; a partial-record drop would
        // desynchronise it permanently).
        std::vector<livewire::WireRecord> got;
        waitUntil( [&]{ cli.poll( got ); return got.size() > 1000; }, 5000 );
        check( !got.empty(), "reader resumes and receives records" );

        // Drop-oldest means `a` may JUMP -- that is the drop, not a bug. What
        // must hold is that it never goes backwards and that every record
        // still reconstructs exactly, which is what byte misalignment would
        // destroy. A reader that had slipped by a few bytes would read
        // fields out of neighbouring records and fail both.
        bool aligned = true;
        for( size_t i = 0; i < got.size(); ++i ) {
            livewire::WireRecord expect = makeTestRecord( got[i].a - 1000 );
            if( std::memcmp( &expect, &got[i], sizeof(expect) ) != 0
                || ( i > 0 && got[i].a <= got[i - 1].a ) ) {
                aligned = false;
                std::cout << "    alignment lost at " << i << ": a=" << got[i].a << "\n";
                break;
            }
        }
        check( aligned, "record alignment and content survive a drop burst" );

        // And the drop must be a clean excision of whole records, not a
        // gradual leak -- if it were, the surviving stream would show many
        // small gaps rather than the few large ones a ring wrap produces.
        int nGaps = 0;
        for( size_t i = 1; i < got.size(); ++i ) {
            if( got[i].a != got[i - 1].a + 1 )
                ++nGaps;
        }
        std::cout << "    " << got.size() << " records received across " << nGaps
                   << " gap(s)\n";

        std::cout << "    " << pub.summary();
    }

    // -------------------------------------------------------------------
    // 4. Version-2 channel-geometry preamble round-trips.
    // -------------------------------------------------------------------
    std::cout << "channel-geometry preamble\n";
    {
        std::vector<int> ids;
        ids.push_back( 10 ); ids.push_back( 20 ); ids.push_back( 30 );

        std::vector<std::vector<livewire::ChannelGeom> > geom( 3 );
        // Unit 0: 4 channels. Unit 1: 1 channel. Unit 2: 0 channels (a real
        // case -- e.g. geometry unavailable for that unit, or the CAR map
        // had no xc/yc fields for its raw ids).
        for( int c = 0; c < 4; ++c ) {
            livewire::ChannelGeom g;
            g.xUm = static_cast<float>( c ) * 1.5f;
            g.yUm = static_cast<float>( c ) * 15.0f + 100.0f;
            geom[0].push_back( g );
        }
        livewire::ChannelGeom g1; g1.xUm = 7.0f; g1.yUm = -42.0f;
        geom[1].push_back( g1 );
        // geom[2] left empty on purpose.

        EventPublisher pub( kTestPort, ids, 30000.0, 0.0, false, 4096 );
        pub.setChannelGeometry( geom, /*templateLength=*/61 );
        if( !pub.start() )
            return 2;

        LiveWireClient cli;
        if( !cli.connect( "127.0.0.1", kTestPort ) ) {
            std::cerr << "client failed to connect: " << cli.lastError() << "\n";
            return 2;
        }

        check( cli.header().version == livewire::kProtocolVersion, "header carries v2" );
        check( cli.header().templateLength == 61, "header templateLength" );
        const std::vector<std::vector<livewire::ChannelGeom> > &got = cli.unitChannelGeom();
        check( got.size() == 3, "geometry table sized nUnits" );
        bool geomOk = got.size() == 3
            && got[0].size() == 4 && got[1].size() == 1 && got[2].size() == 0;
        for( size_t u = 0; geomOk && u < geom.size(); ++u ) {
            for( size_t c = 0; geomOk && c < geom[u].size(); ++c ) {
                geomOk = ( got[u][c].xUm == geom[u][c].xUm && got[u][c].yUm == geom[u][c].yUm );
            }
        }
        check( geomOk, "per-unit channel counts and positions survive the wire" );
    }

    // -------------------------------------------------------------------
    // 5. A version mismatch is refused loudly.
    // -------------------------------------------------------------------
    std::cout << "version mismatch fails loudly\n";
    {
        livewire::SessionHeader h;
        std::memset( &h, 0, sizeof(h) );
        livewire::fillMagic( h );
        h.version = 1;   // this viewer speaks kProtocolVersion == 2
        h.nUnits  = 0;

        std::vector<char> bytes( sizeof(h) );
        std::memcpy( &bytes[0], &h, sizeof(h) );
        std::thread server = serveOnceAndClose( kTestPort + 1, bytes );

        LiveWireClient cli;
        bool connected = cli.connect( "127.0.0.1", kTestPort + 1 );
        server.join();

        check( !connected, "v1 header refused by a v2-speaking client" );
        check( cli.lastError().find( "version" ) != std::string::npos,
               "error message names the version mismatch: '" + cli.lastError() + "'" );
    }

    // -------------------------------------------------------------------
    // 6. A preamble truncated mid-way through the NEW arrays is refused
    //    loudly, not misparsed as if it were a shorter valid stream.
    // -------------------------------------------------------------------
    std::cout << "truncated channel-geometry preamble fails loudly\n";
    {
        livewire::SessionHeader h;
        std::memset( &h, 0, sizeof(h) );
        livewire::fillMagic( h );
        h.version = livewire::kProtocolVersion;
        h.nUnits  = 5;   // promises 5 unit ids + 5 nChannels entries

        std::vector<char> bytes( sizeof(h) );
        std::memcpy( &bytes[0], &h, sizeof(h) );

        std::vector<int32_t> ids( 5 );
        for( int i = 0; i < 5; ++i ) ids[i] = 100 + i;
        bytes.insert( bytes.end(), reinterpret_cast<char*>( &ids[0] ),
                      reinterpret_cast<char*>( &ids[0] ) + ids.size() * sizeof(int32_t) );

        // Only 2 of the promised 5 int32 channel counts, then the
        // connection just closes -- exactly what a peer crashing mid-send
        // would produce.
        std::vector<int32_t> partialCounts( 2, 3 );
        bytes.insert( bytes.end(), reinterpret_cast<char*>( &partialCounts[0] ),
                      reinterpret_cast<char*>( &partialCounts[0] ) + partialCounts.size() * sizeof(int32_t) );

        std::thread server = serveOnceAndClose( kTestPort + 2, bytes );

        LiveWireClient cli;
        bool connected = cli.connect( "127.0.0.1", kTestPort + 2 );
        server.join();

        check( !connected, "truncated channel-count preamble refused" );
        check( cli.lastError().find( "channel-count" ) != std::string::npos,
               "error message names the channel-count preamble: '" + cli.lastError() + "'" );
    }

    // -------------------------------------------------------------------
    // 7. kWireAmpChannel interleaved with kWireSpike survives the wire,
    //    every field routed to the record it belongs to.
    // -------------------------------------------------------------------
    std::cout << "amplitude records interleaved with spike records\n";
    {
        std::vector<int> ids; ids.push_back( 5 ); ids.push_back( 9 );
        std::vector<std::vector<livewire::ChannelGeom> > geom( 2 );
        for( int c = 0; c < 3; ++c ) {
            livewire::ChannelGeom g; g.xUm = 0.0f; g.yUm = static_cast<float>( c ) * 15.0f;
            geom[0].push_back( g );
            geom[1].push_back( g );
        }

        EventPublisher pub( kTestPort + 3, ids, 30000.0, 0.0, false, 4096 );
        pub.setChannelGeometry( geom, 21 );
        if( !pub.start() )
            return 2;

        LiveWireClient cli;
        if( !cli.connect( "127.0.0.1", kTestPort + 3 ) )
            return 2;
        waitUntil( [&]{ return pub.hasClient(); }, 2000 );

        std::vector<livewire::WireRecord> sent;
        // Interleave: spike(unit5) - amp(unit5,ch0) - amp(unit5,ch1) -
        // spike(unit9) - amp(unit5,ch2) - amp(unit9,ch0) - ...
        sent.push_back( livewire::makeRecord( livewire::kWireSpike, livewire::kStreamImec,
                                               5, 1000, 0.9f, 0.01f ) );
        sent.push_back( livewire::makeRecord( livewire::kWireAmpChannel, livewire::kStreamImec,
                                               5, 1000, 12.5f, 0.01f, /*c=*/0 ) );
        sent.push_back( livewire::makeRecord( livewire::kWireAmpChannel, livewire::kStreamImec,
                                               5, 1000, 30.0f, 0.01f, /*c=*/1 ) );
        sent.push_back( livewire::makeRecord( livewire::kWireSpike, livewire::kStreamImec,
                                               9, 1050, 0.8f, 0.02f ) );
        sent.push_back( livewire::makeRecord( livewire::kWireAmpChannel, livewire::kStreamImec,
                                               5, 1000, 8.0f, 0.01f, /*c=*/2 ) );
        sent.push_back( livewire::makeRecord( livewire::kWireAmpChannel, livewire::kStreamImec,
                                               9, 1050, 5.0f, 0.02f, /*c=*/0 ) );
        for( size_t i = 0; i < sent.size(); ++i )
            pub.publish( sent[i] );

        std::vector<livewire::WireRecord> got;
        waitUntil( [&]{ cli.poll( got ); return got.size() >= sent.size(); }, 5000 );

        check( got.size() == sent.size(), "all interleaved records arrived" );
        bool identical = ( got.size() == sent.size() );
        for( size_t i = 0; identical && i < sent.size(); ++i )
            identical = ( std::memcmp( &sent[i], &got[i], sizeof(livewire::WireRecord) ) == 0 );
        check( identical, "interleaved spike/amplitude records byte-identical and in order" );

        bool typesOk = got.size() == sent.size();
        int nSpike = 0, nAmp = 0;
        for( size_t i = 0; typesOk && i < got.size(); ++i ) {
            if( got[i].type == livewire::kWireSpike ) ++nSpike;
            else if( got[i].type == livewire::kWireAmpChannel ) ++nAmp;
            else typesOk = false;
        }
        check( typesOk && nSpike == 2 && nAmp == 4, "record types distinguishable after the mix" );
    }

    // -------------------------------------------------------------------
    // 8. DriftTracker groups kWireAmpChannel records into spikes by
    //    (unit, sampleIndex) even when two spikes' channel records
    //    arrive interleaved with each other (not via a socket -- this is
    //    the grouping logic itself, independent of transport).
    // -------------------------------------------------------------------
    std::cout << "DriftTracker groups interleaved amplitude records correctly\n";
    {
        std::vector<int> ids; ids.push_back( 1 ); ids.push_back( 2 );
        std::vector<std::vector<livewire::ChannelGeom> > geom( 2 );
        // Two channels per unit, 100 um apart, so a centroid is easy to
        // hand-verify: amp-weighted centroid over channels at y=0 and
        // y=100.
        for( int u = 0; u < 2; ++u ) {
            livewire::ChannelGeom a; a.xUm = 0; a.yUm = 0.0f;
            livewire::ChannelGeom b; b.xUm = 0; b.yUm = 100.0f;
            geom[u].push_back( a );
            geom[u].push_back( b );
        }

        DriftTracker dt;
        // minBinsToInclude=1 and a huge bin so this single-bin case is
        // enough to inspect the pooled result directly (no need to
        // manufacture 4+ bins just to exercise the grouping logic).
        dt.configure( ids, geom, /*binS=*/1e9, /*nTop=*/8, /*minBinsToInclude=*/1 );
        dt.setSampleRate( 30000.0 );

        // Unit 1's spike at sample 100: channel 0 amp=10, channel 1 amp=30.
        // Median=20, so amp-median = {0(clamped), 10}; weight on channel1
        // only -> centroid = 100 um exactly.
        // Unit 2's spike at sample 100: channel 0 amp=30, channel 1 amp=10.
        // Symmetric -> centroid = 0 um exactly.
        // Sent interleaved: unit1/ch0, unit2/ch0, unit1/ch1, unit2/ch1.
        dt.onAmpChannel( 1, 100, 0, 10.0f );
        dt.onAmpChannel( 2, 100, 0, 30.0f );
        dt.onAmpChannel( 1, 100, 1, 30.0f );
        dt.onAmpChannel( 2, 100, 1, 10.0f );

        check( dt.nSpikesCompleted() == 2, "both interleaved spike groups completed" );
        check( dt.nAmpRecordsSeen() == 4, "all 4 amplitude records counted" );

        // The actual per-spike centroid math, checked directly (trace()'s
        // pooled output is trivially 0 for a single bin -- see
        // unitBinMean()'s doc comment -- so it would pass even if the
        // centroid computation were wrong).
        double c1 = dt.unitBinMean( 0, 0 );   // unit id 1 -> index 0
        double c2 = dt.unitBinMean( 1, 0 );   // unit id 2 -> index 1
        std::cout << "    unit1 centroid=" << c1 << " um (expect 100), "
                      "unit2 centroid=" << c2 << " um (expect 0)\n";
        check( std::fabs( c1 - 100.0 ) < 1e-6, "unit1's centroid (median-subtracted, top-channel-weighted) is 100 um" );
        check( std::fabs( c2 - 0.0 ) < 1e-6, "unit2's centroid is 0 um (symmetric amplitudes)" );

        DriftTracker::Trace tr = dt.trace();
        check( tr.nUnitsPooled == 2, "both units made it into the pool" );
        check( tr.tCenterS.size() == 1 && std::fabs( tr.motionUm[0] ) < 1e-9,
               "single-bin pooled trace centred at 0, as it trivially must be" );
    }

    // -------------------------------------------------------------------
    // 9. DriftPool::pooledMedianMotion matches pooled_com_motion's own
    //    pooling output on a fixture from gen_drift_fixture.py.
    // -------------------------------------------------------------------
    std::cout << "DriftPool vs FilterGen/drift_estimate.pooled_com_motion fixture\n";
    if( argc < 2 ) {
        ++g_skipped;
        std::cout << "  SKIP  no fixture path given -- run:\n"
                      "        python FilterGen\\gen_drift_fixture.py --out drift_fixture.bin --bin-s 5.0 --spikes-per-unit 1500\n"
                      "        TestLiveWireRoundtrip.exe drift_fixture.bin\n";
    }
    else {
        std::ifstream fh( argv[1], std::ios::binary );
        if( !fh.is_open() ) {
            std::cerr << "could not open fixture '" << argv[1] << "'\n";
            return 2;
        }

        int32_t nUnits = 0, nTime = 0;
        fh.read( reinterpret_cast<char*>( &nUnits ), sizeof(int32_t) );
        fh.read( reinterpret_cast<char*>( &nTime ), sizeof(int32_t) );

        std::vector<std::vector<double> > Y( nUnits, std::vector<double>( nTime ) );
        for( int u = 0; u < nUnits; ++u )
            fh.read( reinterpret_cast<char*>( &Y[u][0] ), nTime * sizeof(double) );

        std::vector<double> grid( nTime ), motionExpect( nTime );
        fh.read( reinterpret_cast<char*>( &grid[0] ), nTime * sizeof(double) );
        fh.read( reinterpret_cast<char*>( &motionExpect[0] ), nTime * sizeof(double) );

        check( fh.good() || fh.eof(), "fixture read completely" );

        std::vector<double> motion = pooledMedianMotion( Y, grid );

        double maxErr = 0.0;
        check( motion.size() == motionExpect.size(), "pooled trace has the expected length" );
        for( size_t t = 0; t < motion.size() && t < motionExpect.size(); ++t )
            maxErr = std::max( maxErr, std::fabs( motion[t] - motionExpect[t] ) );

        int nNanY = 0;
        for( int u = 0; u < nUnits; ++u )
            for( int t = 0; t < nTime; ++t )
                if( std::isnan( Y[u][t] ) ) ++nNanY;

        std::cout << "    nUnits=" << nUnits << " nTime=" << nTime
                   << " (" << nNanY << " NaN entries in Y, so the gap-fill path is exercised)\n"
                   << "    max |motion - motion_expect| = " << maxErr << " um\n";

        const double tol = 1e-9;
        check( maxErr < tol, "pooledMedianMotion matches pooled_com_motion's pooling exactly" );
    }

    // A bare run skips the ONE check that compares this port against the
    // Python reference, and a plain "PASS" on that run reads as "the port is
    // verified" when nothing numerical was verified at all. Say so in the
    // summary line rather than letting a green bar imply more than it did.
    if( g_failures != 0 )
        std::cout << "FAIL\n";
    else if( g_skipped != 0 )
        std::cout << "PASS (INCOMPLETE -- " << g_skipped
                   << " check(s) skipped; the DriftPool-vs-Python equivalence was NOT run.\n"
                      "       Generate the fixture and pass its path to run it.)\n";
    else
        std::cout << "PASS\n";
    return g_failures == 0 ? 0 : 1;
}
